### ISSUE TITLE
latex毕业论文在zstu的接受度高吗

### ISSUE THREAD

**Issue by flottant** [zweix123/zstu-graduation-thesis-latex-template#1]
听说有不少老师只接受word版本的论文，具体的情况如何呢？

**Comment by zweix123** [comment]
感谢对本项目的关注，个人最近比较忙碌，没有及时回复万分抱歉。

您的问题是一个很经典的问题，在我选择工具是也有类似的疑问。

据我所知，sw老师是非常推荐LaTeX的，而他是院长，我也接触其他老师的学生也使用LaTeX完成论文，具体的，还是建议和老师充分沟通。

我的建议也写在[README](https://github.com/zweix123/zstu-graduation-thesis-latex-template?tab=readme-ov-file#tips)里。
